[#IOCOM-1200] New external api specs
pagopa/io-functions-service-messages pull request #74
Opened 2024-03-22 11:24 UTC by acuiuli

#### List of Changes

- [new external api specifications](https://github.com/pagopa/io-functions-service-messages/commit/74b992e6c2a8e7c574b1be9ee12dde64f8d473fc)

#### Motivation and Context

A new specification file has been created to send to external people without exposing fields that they do not need to send because are managed internally

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-03-22 12:18 UTC, Garma00 submitted a review, later dismissed

2024-03-22 12:46 UTC, michaeldisaro requested changes

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +  /notify:
we should remove this endpoint from the external api

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +                "is_lollipop_enabled": true,
```suggestion
                "is_lollipop_enabled": false,
```

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +                "name": "string",
```suggestion
                "name": "Descriptive configuration name",
```

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +                "description": "string",
```suggestion
                "description": "Configuration description.",
```

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +                "description": "string",
in all examples

2024-03-22 12:46 UTC, michaeldisaro commented on openapi/index_external.yaml
> +                "is_lollipop_enabled": true,
in all examples

2024-03-22 12:59 UTC, michaeldisaro approved these changes

2024-03-22 13:01 UTC, michaeldisaro requested changes

2024-03-22 13:01 UTC, michaeldisaro commented on openapi/index_external.yaml
> +  description: >
Is this experimental? I don't think so. Maybe we should put here a description.

2024-03-26 08:38 UTC, michaeldisaro approved these changes

2024-03-26 08:38 UTC, Garma00 approved these changes

2024-03-26 08:39 UTC, merged